import { validateMultiFasta } from './multifasta-checker'

const validMultifastas = [
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
>EIABBJEP_00002 3-methyl-2-oxobutanoate hydroxymethyltransferase
MKPTTISLLQKYKQEKKRFATITAYDYSFAKLFADEGLNVMLVGDSLGMTVQGHDSTLPV
TVADIAYHTAAVRRGAPNCLLLADLPFMAYATPEQAFENAATVMRAGANMVKIEGGEWLV
ETVQMLTERAVPVCGHLGLTPQSVNIFGGYKVQGRGDEAGDQLLSDALALEAAGAQLLVL
ECVPVELAKRITEALAIPVIGIGAGNVTDGQILVMHDAFGITGGHIPKFAKNFLAETGDI
RAAVRQYMAEVESGVYPGEEHSFH`,
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
  `,
  `>Contig_28_703.295_1 # 556 # 699 # 1 # ID=1_1;partial=00;start_type=GTG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.597
MAKAAPWTKTDAQVRKRGEQTGLDTLVVHAVNDVDLEVVPLRRGFRS*`,
  `>Test
MAKAA-`,
]

const invalidMultiFastas = [
  '',
  `MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
`,
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
invalidcharacters`,
]

test.each(validMultifastas)('Multifasta %s is valid', (mf) => {
  expect(validateMultiFasta(mf)).toBe(true)
})

test.each(invalidMultiFastas)('Multifasta %s is invalid', (mf) => {
  expect(validateMultiFasta(mf)).toBe(false)
})
