import { validateMultiFasta } from './multifasta-checker'

const validMultifastas = [
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
>EIABBJEP_00002 3-methyl-2-oxobutanoate hydroxymethyltransferase
MKPTTISLLQKYKQEKKRFATITAYDYSFAKLFADEGLNVMLVGDSLGMTVQGHDSTLPV
TVADIAYHTAAVRRGAPNCLLLADLPFMAYATPEQAFENAATVMRAGANMVKIEGGEWLV
ETVQMLTERAVPVCGHLGLTPQSVNIFGGYKVQGRGDEAGDQLLSDALALEAAGAQLLVL
ECVPVELAKRITEALAIPVIGIGAGNVTDGQILVMHDAFGITGGHIPKFAKNFLAETGDI
RAAVRQYMAEVESGVYPGEEHSFH`,
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
  `,
]

const invalidMultiFastas = [
  '',
  `MGEYSSGTIKNGASPVPFDISLQNCIRVRNIETKLVTGKVGTQNTQLLGNTLTGSTAAKG
VGVLIEGLATSKNPLMTLKPNDTNSVYIDYETEDDTSDGVYPNQGNGTSQPLHFQATLKQ
DGNIAIEPGEFKATSTFQVTYP
`,
  `>EIABBJEP_00001 putative fimbrial-like protein YadC
invalid characters 123`,
]

test.each(validMultifastas)('Multifasta %s is valid', (mf) => {
  expect(validateMultiFasta(mf)).toBe(true)
})

test.each(invalidMultiFastas)('Multifasta %s is invalid', (mf) => {
  expect(validateMultiFasta(mf)).toBe(false)
})
